language: python
python:
  - "3.6"

services:
  - docker

install:
  - pip install docker-compose

before_script:
  - cp .env.test .env

script:
  - docker-compose --file docker-compose.test.yml run --rm test
    bash -c "pip3 install tox && tox"
  - docker-compose --file docker-compose.test.yml run --rm test
    node_modules/.bin/eslint --config .eslintrc 'osm_validator_front/js/**'
