language: python
python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - osm2pgsql
      - osmctools
      - postgresql-9.6-postgis-2.3

services:
  - postgresql
  - redis-server

install:
  - pip install tox
  - npm install

before_script:
  - psql -U postgres -c "CREATE DATABASE osmvalidatortest;"
  - psql -U postgres -d osmvalidatortest -c "CREATE EXTENSION postgis;"
  - psql -U postgres -d osmvalidatortest -c "CREATE EXTENSION hstore;"
  - psql -U postgres -c "CREATE USER test WITH PASSWORD 'test';"


script:
  - export $(cat .env.test | xargs) && tox
  - ./node_modules/.bin/eslint --config ./.eslintrc 'osm_validator_front/js/**'
